encryption_key: 'This is a key that is 256 bits!!'

environment: 'local'
app_host: 'http://localhost:3001/'

default:
  api_host: 'http://localhost:3000'

maestrano-uat:
  api_host: 'http://localhost:3000'
